<?php

namespace App\Services;

class CountriesService
{
    /**
     * Get list of countries/nationalities
     * 
     * @return array
     */
    public static function getCountries(): array
    {
        return [
            'Afghan' => 'Afghan',
            'Albanian' => 'Albanian',
            'Algerian' => 'Algerian',
            'American' => 'American',
            'Andorran' => 'Andorran',
            'Angolan' => 'Angolan',
            'Argentine' => 'Argentine',
            'Armenian' => 'Armenian',
            'Australian' => 'Australian',
            'Austrian' => 'Austrian',
            'Azerbaijani' => 'Azerbaijani',
            'Bahamian' => 'Bahamian',
            'Bahraini' => 'Bahraini',
            'Bangladeshi' => 'Bangladeshi',
            'Barbadian' => 'Barbadian',
            'Belarusian' => 'Belarusian',
            'Belgian' => 'Belgian',
            'Belizean' => 'Belizean',
            'Beninese' => 'Beninese',
            'Bhutanese' => 'Bhutanese',
            'Bolivian' => 'Bolivian',
            'Bosnian' => 'Bosnian',
            'Botswanan' => 'Botswanan',
            'Brazilian' => 'Brazilian',
            'British' => 'British',
            'Bruneian' => 'Bruneian',
            'Bulgarian' => 'Bulgarian',
            'Burkinabé' => 'Burkinabé',
            'Burundian' => 'Burundian',
            'Cambodian' => 'Cambodian',
            'Cameroonian' => 'Cameroonian',
            'Canadian' => 'Canadian',
            'Cape Verdean' => 'Cape Verdean',
            'Central African' => 'Central African',
            'Chadian' => 'Chadian',
            'Chilean' => 'Chilean',
            'Chinese' => 'Chinese',
            'Colombian' => 'Colombian',
            'Comorian' => 'Comorian',
            'Congolese' => 'Congolese',
            'Costa Rican' => 'Costa Rican',
            'Croatian' => 'Croatian',
            'Cuban' => 'Cuban',
            'Cypriot' => 'Cypriot',
            'Czech' => 'Czech',
            'Danish' => 'Danish',
            'Djibouti' => 'Djibouti',
            'Dominican' => 'Dominican',
            'Dutch' => 'Dutch',
            'East Timorese' => 'East Timorese',
            'Ecuadorian' => 'Ecuadorian',
            'Egyptian' => 'Egyptian',
            'Salvadoran' => 'Salvadoran',
            'Emirati' => 'Emirati',
            'Equatorial Guinean' => 'Equatorial Guinean',
            'Eritrean' => 'Eritrean',
            'Estonian' => 'Estonian',
            'Ethiopian' => 'Ethiopian',
            'Fijian' => 'Fijian',
            'Finnish' => 'Finnish',
            'French' => 'French',
            'Gabonese' => 'Gabonese',
            'Gambian' => 'Gambian',
            'Georgian' => 'Georgian',
            'German' => 'German',
            'Ghanaian' => 'Ghanaian',
            'Greek' => 'Greek',
            'Grenadian' => 'Grenadian',
            'Guatemalan' => 'Guatemalan',
            'Guinean' => 'Guinean',
            'Guinea-Bissauan' => 'Guinea-Bissauan',
            'Guyanese' => 'Guyanese',
            'Haitian' => 'Haitian',
            'Honduran' => 'Honduran',
            'Hungarian' => 'Hungarian',
            'Icelander' => 'Icelander',
            'Indian' => 'Indian',
            'Indonesian' => 'Indonesian',
            'Iranian' => 'Iranian',
            'Iraqi' => 'Iraqi',
            'Irish' => 'Irish',
            'Israeli' => 'Israeli',
            'Italian' => 'Italian',
            'Ivorian' => 'Ivorian',
            'Jamaican' => 'Jamaican',
            'Japanese' => 'Japanese',
            'Jordanian' => 'Jordanian',
            'Kazakhstani' => 'Kazakhstani',
            'Kenyan' => 'Kenyan',
            'Kiribatian' => 'Kiribatian',
            'Korean' => 'Korean',
            'Kuwaiti' => 'Kuwaiti',
            'Kyrgyz' => 'Kyrgyz',
            'Laotian' => 'Laotian',
            'Latvian' => 'Latvian',
            'Lebanese' => 'Lebanese',
            'Lesotho' => 'Lesotho',
            'Liberian' => 'Liberian',
            'Libyan' => 'Libyan',
            'Liechtensteiner' => 'Liechtensteiner',
            'Lithuanian' => 'Lithuanian',
            'Luxembourger' => 'Luxembourger',
            'Macedonian' => 'Macedonian',
            'Malagasy' => 'Malagasy',
            'Malawian' => 'Malawian',
            'Malaysian' => 'Malaysian',
            'Maldivian' => 'Maldivian',
            'Malian' => 'Malian',
            'Maltese' => 'Maltese',
            'Marshallese' => 'Marshallese',
            'Martinican' => 'Martinican',
            'Mauritanian' => 'Mauritanian',
            'Mauritian' => 'Mauritian',
            'Mexican' => 'Mexican',
            'Micronesian' => 'Micronesian',
            'Moldovan' => 'Moldovan',
            'Monegasque' => 'Monegasque',
            'Mongolian' => 'Mongolian',
            'Montenegrin' => 'Montenegrin',
            'Moroccan' => 'Moroccan',
            'Mozambican' => 'Mozambican',
            'Myanmarese' => 'Myanmarese',
            'Namibian' => 'Namibian',
            'Nauruan' => 'Nauruan',
            'Nepalese' => 'Nepalese',
            'New Zealander' => 'New Zealander',
            'Nicaraguan' => 'Nicaraguan',
            'Nigerian' => 'Nigerian',
            'Nigerien' => 'Nigerien',
            'Norwegian' => 'Norwegian',
            'Omani' => 'Omani',
            'Pakistani' => 'Pakistani',
            'Palauan' => 'Palauan',
            'Palestinian' => 'Palestinian',
            'Panamanian' => 'Panamanian',
            'Papua New Guinean' => 'Papua New Guinean',
            'Paraguayan' => 'Paraguayan',
            'Peruvian' => 'Peruvian',
            'Philippine' => 'Philippine',
            'Polish' => 'Polish',
            'Portuguese' => 'Portuguese',
            'Qatari' => 'Qatari',
            'Romanian' => 'Romanian',
            'Russian' => 'Russian',
            'Rwandan' => 'Rwandan',
            'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
            'Saint Lucian' => 'Saint Lucian',
            'Saint Vincent and Grenadine' => 'Saint Vincent and Grenadine',
            'Samoan' => 'Samoan',
            'Sammarinese' => 'Sammarinese',
            'Sao Tomean' => 'Sao Tomean',
            'Saudi Arabian' => 'Saudi Arabian',
            'Senegalese' => 'Senegalese',
            'Serbian' => 'Serbian',
            'Seychellois' => 'Seychellois',
            'Sierra Leonean' => 'Sierra Leonean',
            'Singaporean' => 'Singaporean',
            'Slovak' => 'Slovak',
            'Slovenian' => 'Slovenian',
            'Solomon Islander' => 'Solomon Islander',
            'Somali' => 'Somali',
            'South African' => 'South African',
            'South Sudanese' => 'South Sudanese',
            'Spanish' => 'Spanish',
            'Sri Lankan' => 'Sri Lankan',
            'Sudanese' => 'Sudanese',
            'Surinamese' => 'Surinamese',
            'Swazi' => 'Swazi',
            'Swedish' => 'Swedish',
            'Swiss' => 'Swiss',
            'Syrian' => 'Syrian',
            'Taiwanese' => 'Taiwanese',
            'Tajik' => 'Tajik',
            'Tanzanian' => 'Tanzanian',
            'Thai' => 'Thai',
            'Timorese' => 'Timorese',
            'Togolese' => 'Togolese',
            'Tongan' => 'Tongan',
            'Trinidadian' => 'Trinidadian',
            'Tunisian' => 'Tunisian',
            'Turkish' => 'Turkish',
            'Turkmen' => 'Turkmen',
            'Tuvaluan' => 'Tuvaluan',
            'Ugandan' => 'Ugandan',
            'Ukrainian' => 'Ukrainian',
            'Uruguayan' => 'Uruguayan',
            'Uzbek' => 'Uzbek',
            'Vanuatuan' => 'Vanuatuan',
            'Venezuelan' => 'Venezuelan',
            'Vietnamese' => 'Vietnamese',
            'Welsh' => 'Welsh',
            'Yemenite' => 'Yemenite',
            'Zambian' => 'Zambian',
            'Zimbabwean' => 'Zimbabwean',
        ];
    }

    /**
     * Get countries list as array for select options
     * 
     * @return array
     */
    public static function getCountriesForSelect(): array
    {
        return self::getCountries();
    }

    /**
     * Check if nationality is valid
     * 
     * @param string $nationality
     * @return bool
     */
    public static function isValidNationality(string $nationality): bool
    {
        return isset(self::getCountries()[$nationality]);
    }
}
